aws:
  dynamodb:
    tableName: "ads"
    secretKey: "12345"
    accessKey: "local"
    endpoint: "http://localhost:8000"
    region: "us-west-2"

security:
  token:
    enabled: true
    bypass: "test"
    keyFilePath: "public-keys/local-ads-service-public.pem"

server:
  error:
    include-stacktrace: never